name: ReadTheWeb
favicon: null
layout_spectrum: 0.22555
typography_spectrum: 0.33546
title: 'Read more about web, tech and life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#247686'
    - '#005555'
    - '#000000'
    - '#000080'
    - '#004080'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
