name: ReadTheWeb
favicon: null
layout_spectrum: 0.8108170367777348
typography_spectrum: 0.9449507675599307
title: 'Read more about web, tech and life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6046585566364229
  lightness: 0.005269976332783699
  saturation: 0.08136279624886811
  rhythmicContrast: 0.9197876828256994
purpose: []
